### ISSUE TITLE
Failed Graphs On New Device

### ISSUE THREAD

**Issue by ForestFeather** [jprochazka/adsb-receiver#293]
I've set up the receiver on a new device - a CHIP $9 computer board.  It's all working fine save three of the charts not functioning - core temperature, and the two disk charts.  I suspect this is due to the microprocessor not supporting a core temperature (though another chip on the board does) and it having inbuilt flash, rather than microSD or HDD.  df reports it as 'ubi0:rootfs' of a 'ubifs' type.

**Comment by Romeo-Golf** [comment]
Hi, thanks for the report and while I'm not aware of anyone having tried the adsb-receiver scripts on a CHIP it's great to know that it mostly works :)

From some quick research it should be fairly eàsy to get equivalent temp and file system graphs from tgis platform, and perhaps add a framework to help detect other non-Pi platforms!

If memory serves me correctly I have a CHIP lying around somewhere that I hadnt found a use for so will see if I can track it down to help testing...

In the mean time are you able to share the steps you took to install adsb-receiver on the CHIP so we can add any relevant steps to the documentation and/or install scripts?

**Comment by Romeo-Golf** [comment]
(links from my initial research)

This should get the CPU temp, or somewhere close:

https://bbs.nextthing.co/t/how-to-check-the-temperature-of-chip/1738/41


Looks like there may be a setting required to disable some kind of overload protection:

https://bbs.nextthing.co/t/c-h-i-p-rtl-sdr-webserver-a-no-go/13466


And to set a static Mac address to ensure starts reported to feeder sites is attributed correctly:

https://bbs.nextthing.co/t/solved-can-i-disable-on-board-ethernet-gadget-adapers-or-assign-a-fixed-mac/5427

**Comment by ForestFeather** [comment]
That first link I already had loaded, actually, haha, to see what was available myself.  It's the AX209 power controller, not the micro, but it's what we got.

For this setup, I've actually got a powered USB hub to a ProStick - doing it straight resulted in the board shutting down.  Had to use a 2.0 hub as well, a 3.0 hub was also drawing too much juice.  Hadn't tried the overload protection disable, but I've got 3 more and was intending to with another unit eventually.  Haven't had any mac address problems with them shifting on me yet though.

As for the setup, I installed the main headless image and set up wireless, at which point I installed:
* dump1090-mutability
* flightware/piaware tracker
* planefinder tracker
* Advanced setup with remote MySQL database

I also manually specified my gain in the dump1090-mutability file, but I doubt that'll have had any impact here.

**Comment by Romeo-Golf** [comment]
Thanks for the feedback, will make sure to test with a USB 2.0 powered hub and use a prostick for consistency :)

I'm not sure of Joe's thinking on adding the ability to specify the dump1090 gain during setup but if this is something you would find useful then a feature request would be a good place to discuss this..

Also would you mind sharing the output of 'cat /proc/cpuinfo' to assist with hardware identification?

Thanks

**Comment by ForestFeather** [comment]
Certainly; here's said output:
╟──╢ $ > cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 1001.88
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc08
CPU revision    : 2

Hardware        : Allwinner sun4i/sun5i Families
Revision        : 0000
Serial          : 1625428201c220ee

**Comment by Romeo-Golf** [comment]
So it looks like support for "/sys/class/thermal/thermal_zone0/temp" disappeared at some point and the nearest approximation is "/sys/class/hwmon/hwmon0/temp1_input"...  

Would you mind sharing the output of 'cat "/sys/class/hwmon/hwmon0/temp1_input' to confirm this is a 5 digit number that looks like 1/100's of a degree C?

I am updating the graph generation with basic hardware detection and the assumption the above value is usable on all devices which list "Hardware : Allwinner sun4i/sun5i Families" in /proc/cpuinfo...  but if not we may need to look into using  'axp209 --temperature' ;)

**Comment by Romeo-Golf** [comment]
I have pushed what I hope should be a fix into my 2.5.1 branch, would you be able to test cloning my fork with:

git clone -b 2.6.0 https://github.com/Romeo-Golf/adsb-receiver.git

And then updating by running the install script with:

cd adsb-receiver && ./install -b 2.6.0

**Comment by ForestFeather** [comment]
Attempted this, but no dice - system still showing 2.5.0 as version.  Could be my attempt, though.

**Comment by Romeo-Golf** [comment]
Hi,

Unfortunately the portal updates for 2.6.0 are still pending; however the graph creation script in my 2.6.0 branch *should* detect the CHIP platform and generate the temperature/disk graphs using the same file names as they would be on Raspberry Pi... is anything at all displayed for these graphs in the portal performance graphs tab?

Thanks.

**Comment by ForestFeather** [comment]
Ah, found the problem on this - it flips itself back to the 'master' branch.  The install flag doesn't seem to do anything.  Even manually switching to 2.6.0, the install script runs it back to 'master'.

**Comment by Romeo-Golf** [comment]
Using the 2.6.0 branch code the install script accepts the -b flag to override the hard coded reference to the master branch...

It could be there are remnants of the old code so if your happy to try a full reinstall then please try the following:

rm -rf ~/adsb-receiver
git clone -b 2.6.0 https://github.com/Romeo-Golf/adsb-receiver.git
cd ~/adsb-receiver
git checkout origin/2.6.0
./install.sh -b 2.6.0

Thanks.

**Comment by ForestFeather** [comment]
Executed.  Doesn't seem to have changed anything, however, the graphs aren't being generated.

Let me know what you'd like me to try - I'll keep at it.

As a note too, for these devices, we may want to examine file usage.  After it had run without restart for about 10 days the whole thing locked up on writing the adsb json with "too many files".  A restart fixed it, but it should be checked.

**Comment by Romeo-Golf** [comment]
Thanks for the update, would you mind sharing the output of the following:

sudo bash -x /home/pi/adsb-receiver/build/portal/graphs/make-collectd-graphs.sh 24h

Not sure about the 'too many files' issues, if it happens again would you mind trying to capture the exact error text?

Thanks.

**Comment by ForestFeather** [comment]
Incoming output, it's quite wordy.

++ grep server.document-root
++ /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -p
+ RAWDOCUMENTROOT='    server.document-root           = "/var/www/html"'
++ sed 's/.*"\(.*\)"[^"]*$/\1/'
+ DOCUMENTROOT=/var/www/html
+ renice -n 5 -p 9797
9797 (process ID) old priority 0, new priority 5
+ period=24h
+ step=
++ date '+%m/%d/%y %H:%M %Z'
+ nowlit='01/18/17 14:44 CST'
+ dump1090_receiver_graphs localhost localhost ADS-B 24h ''
+ dump1090_graphs localhost localhost ADS-B 24h ''
+ aircraft_graph /var/www/html/graphs/dump1090-localhost-aircraft-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-aircraft-24h.png --start end-24h --width 480 --height 200 --step '' --title 'ADS-B Aircraft Seen / Tracked' --vertical-label Aircraft --lower-limit 0 --units-exponent 0 TEXTALIGN:center DEF:all=/var/lib/collectd/rrd
/localhost/dump1090-localhost/dump1090_aircraft-recent.rrd:total:AVERAGE DEF:pos=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_aircraft-recent.rrd:positions:AVERAGE DEF:mlat=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_mlat-recent.rrd:value:A
VERAGE CDEF:noloc=all,pos,- VDEF:avgac=all,AVERAGE VDEF:maxac=all,MAXIMUM 'AREA:all#00FF00:Aircraft Seen / Tracked,   ' 'GPRINT:avgac:Average\:%3.0lf     ' 'GPRINT:maxac:Maximum\:%3.0lf             ' 'LINE1:pos#0000FF:w/ Positions' 'LINE1:noloc#FF0000:w/o Positions' LINE
1:mlat#000000:mlat --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ aircraft_message_rate_graph /var/www/html/graphs/dump1090-localhost-aircraft_message_rate-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-aircraft_message_rate-24h.png --start end-24h --width 428 --height 200 --step '' --title 'ADS-B Message Rate / Aircraft' --vertical-label Messages/Aircraft/Second --right-axis-label Aircraft --lower-limit 0 --units-
exponent 0 --right-axis 10:0 TEXTALIGN:center DEF:aircrafts=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_aircraft-recent.rrd:total:AVERAGE DEF:messages=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE CD
EF:provisional=messages,aircrafts,/ CDEF:rate=aircrafts,0,GT,provisional,0,IF CDEF:aircrafts10=aircrafts,10,/ VDEF:avgrate=rate,AVERAGE VDEF:maxrate=rate,MAXIMUM 'LINE1:rate#0000FF:Messages / AC' LINE1:avgrate#666666:Average:dashes GPRINT:avgrate:%3.1lf LINE1:maxrate#FF0
000:Maximum 'GPRINT:maxrate:%3.1lf\c' 'LINE1:aircrafts10#990000:Aircraft Seen / Tracked (RHS) \c' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ cpu_graph_dump1090 /var/www/html/graphs/dump1090-localhost-cpu-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-cpu-24h.png --start end-24h --width 480 --height 200 --step '' --title 'ADS-B CPU Utilization' --vertical-label 'CPU %' --lower-limit 0 --rigid DEF:demod=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_c
pu-demod.rrd:value:AVERAGE CDEF:demodp=demod,10,/ DEF:reader=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_cpu-reader.rrd:value:AVERAGE CDEF:readerp=reader,10,/ DEF:background=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_cpu-background.rrd:va
lue:AVERAGE CDEF:backgroundp=background,10,/ AREA:readerp#008000:USB AREA:backgroundp#00C000:Other:STACK 'AREA:demodp#00FF00:Demodulator\c:STACK' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ tracks_graph /var/www/html/graphs/dump1090-localhost-tracks-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-tracks-24h.png --start end-24h --width 480 --height 200 --step '' --title 'ADS-B Tracks Seen' --vertical-label Tracks/Hour --lower-limit 0 --units-exponent 0 DEF:all=/var/lib/collectd/rrd/localhost/dump1090-localhos
t/dump1090_tracks-all.rrd:value:AVERAGE DEF:single=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_tracks-single_message.rrd:value:AVERAGE 'CDEF:hall=all,3600,*' 'CDEF:hsingle=single,3600,*' 'AREA:hsingle#FF0000:Tracks with single message' 'AREA:hall#00FF00:U
nique tracks\c:STACK' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ system_graphs localhost localhost ADS-B 24h ''
+ cpu_graph /var/www/html/graphs/system-localhost-cpu-24h.png /var/lib/collectd/rrd/localhost/aggregation-cpu-average ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-cpu-24h.png --start end-24h --width 1010 --height 200 --step '' --title 'Overall CPU Utilization' --vertical-label 'CPU %' --lower-limit 0 --rigid --units-exponent 0 DEF:idle=/var/lib/collectd/rrd/localhost/aggregatio
n-cpu-average/cpu-idle.rrd:value:AVERAGE DEF:interrupt=/var/lib/collectd/rrd/localhost/aggregation-cpu-average/cpu-interrupt.rrd:value:AVERAGE DEF:nice=/var/lib/collectd/rrd/localhost/aggregation-cpu-average/cpu-nice.rrd:value:AVERAGE DEF:softirq=/var/lib/collectd/rrd/lo
calhost/aggregation-cpu-average/cpu-softirq.rrd:value:AVERAGE DEF:steal=/var/lib/collectd/rrd/localhost/aggregation-cpu-average/cpu-steal.rrd:value:AVERAGE DEF:system=/var/lib/collectd/rrd/localhost/aggregation-cpu-average/cpu-system.rrd:value:AVERAGE DEF:user=/var/lib/c
ollectd/rrd/localhost/aggregation-cpu-average/cpu-user.rrd:value:AVERAGE DEF:wait=/var/lib/collectd/rrd/localhost/aggregation-cpu-average/cpu-wait.rrd:value:AVERAGE CDEF:all=idle,interrupt,nice,softirq,steal,system,user,wait,+,+,+,+,+,+,+ 'CDEF:pinterrupt=100,interrupt,*
,all,/' 'CDEF:pnice=100,nice,*,all,/' 'CDEF:psoftirq=100,softirq,*,all,/' 'CDEF:psteal=100,steal,*,all,/' 'CDEF:psystem=100,system,*,all,/' 'CDEF:puser=100,user,*,all,/' 'CDEF:pwait=100,wait,*,all,/' AREA:pinterrupt#000080:irq AREA:psoftirq#0000C0:softirq:STACK AREA:pste
al#0000FF:steal:STACK AREA:pwait#C00000:io:STACK AREA:psystem#FF0000:sys:STACK AREA:puser#40FF40:user:STACK 'AREA:pnice#008000:nice\c:STACK' --watermark 'Drawn: 01/18/17 14:44 CST'
1107x284
+ df_root_graph /var/www/html/graphs/system-localhost-df_root-24h.png /var/lib/collectd/rrd/localhost/df-root ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-df_root-24h.png --start end-24h --width 496 --height 200 --step '' --title 'Disk Usage (/)' --vertical-label '' --lower-limit 0 TEXTALIGN:center DEF:used=/var/lib/collectd/rrd/localhost/df-root/df_complex-used.rrd:val
ue:AVERAGE DEF:reserved=/var/lib/collectd/rrd/localhost/df-root/df_complex-reserved.rrd:value:AVERAGE DEF:free=/var/lib/collectd/rrd/localhost/df-root/df_complex-free.rrd:value:AVERAGE CDEF:totalused=used,reserved,+ AREA:totalused#4169E1:Used:STACK 'AREA:free#32C734:Free
\c:STACK' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ disk_io_iops_graph /var/www/html/graphs/system-localhost-disk_io_iops-24h.png /var/lib/collectd/rrd/localhost/disk-mmcblk0 ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-disk_io_iops-24h.png --start end-24h --width 480 --height 200 --step '' --title 'Disk I/O - IOPS' --vertical-label IOPS TEXTALIGN:center DEF:read=/var/lib/collectd/rrd/localhost/disk-mmcblk0/disk_ops.rrd:read:AVERAGE 
DEF:write=/var/lib/collectd/rrd/localhost/disk-mmcblk0/disk_ops.rrd:write:AVERAGE 'CDEF:write_neg=write,-1,*' 'AREA:read#32CD32:Reads ' LINE1:read#336600 'GPRINT:read:MAX:Max\:%4.1lf iops' 'GPRINT:read:AVERAGE:Avg\:%4.1lf iops' 'GPRINT:read:LAST:Current\:%4.1lf iops\c' T
EXTALIGN:center AREA:write_neg#4169E1:Writes LINE1:write_neg#0033CC 'GPRINT:write:MAX:Max\:%4.1lf iops' 'GPRINT:write:AVERAGE:Avg\:%4.1lf iops' 'GPRINT:write:LAST:Current\:%4.1lf iops\c' --watermark 'Drawn: 01/18/17 14:44 CST'
ERROR: opening '/var/lib/collectd/rrd/localhost/disk-mmcblk0/disk_ops.rrd': No such file or directory
+ disk_io_octets_graph /var/www/html/graphs/system-localhost-disk_io_octets-24h.png /var/lib/collectd/rrd/localhost/disk-mmcblk0 ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-disk_io_octets-24h.png --start end-24h --width 480 --height 200 --step '' --title 'Disk I/O - Bandwidth' --vertical-label Bytes/Sec TEXTALIGN:center DEF:read=/var/lib/collectd/rrd/localhost/disk-mmcblk0/disk_octets.rr
d:read:AVERAGE DEF:write=/var/lib/collectd/rrd/localhost/disk-mmcblk0/disk_octets.rrd:write:AVERAGE 'CDEF:write_neg=write,-1,*' 'AREA:read#32CD32:Reads ' LINE1:read#336600 'GPRINT:read:MAX:Max\: %4.1lf %sB/sec' 'GPRINT:read:AVERAGE:Avg\: %4.1lf %SB/sec' 'GPRINT:re[0/909]:Current\: %4.1lf %SB/sec\c' TEXTALIGN:center AREA:write_neg#4169E1:Writes LINE1:write_neg#0033CC 'GPRINT:write:MAX:Max\: %4.1lf %sB/sec' 'GPRINT:write:AVERAGE:Avg\: %4.1lf %SB/sec' 'GPRINT:write:LAST:Current\: %4.1lf %SB/sec\c' --watermark 'Drawn: 01/18/17 14:44 CST'
ERROR: opening '/var/lib/collectd/rrd/localhost/disk-mmcblk0/disk_octets.rrd': No such file or directory
+ eth0_graph /var/www/html/graphs/system-localhost-eth0_bandwidth-24h.png /var/lib/collectd/rrd/localhost/interface-eth0 ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-eth0_bandwidth-24h.png --start end-24h --width 480 --height 200 --step '' --title 'Bandwidth Usage (eth0)' --vertical-label Bytes/Sec TEXTALIGN:center DEF:rx=/var/lib/collectd/rrd/localhost/interface-eth0/if_octets.rrd:rx:AVERAGE DEF:tx=/var/lib/collectd/rrd/localhost/interface-eth0/if_octets.rrd:tx:AVERAGE 'CDEF:tx_neg=tx,-1,*' AREA:rx#32CD32:Incoming LINE1:rx#336600 'GPRINT:rx:MAX:Max\:%8.1lf %s' 'GPRINT:rx:AVERAGE:Avg\:%8.1lf %S' 'GPRINT:rx:LAST:Current\:%8.1lf %Sbytes/sec\c' AREA:tx_neg#4169E1:Outgoing LINE1:tx_neg#0033CC 'GPRINT:tx:MAX:Max\:%8.1lf %S' 'GPRINT:tx:AVERAGE:Avg\:%8.1lf %S' 'GPRINT:tx:LAST:Current\:%8.1lf %Sbytes/sec\c' --watermark 'Drawn: 01/18/17 14:44 CST'
ERROR: opening '/var/lib/collectd/rrd/localhost/interface-eth0/if_octets.rrd': No such file or directory
+ memory_graph /var/www/html/graphs/system-localhost-memory-24h.png /var/lib/collectd/rrd/localhost/memory ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-memory-24h.png --start end-24h --width 496 --height 200 --step '' --lower-limit 0 --title 'Memory Utilization' --vertical-label '' TEXTALIGN:center DEF:buffered=/var/lib/collectd/rrd/localhost/memory/memory-buffered.rrd:value:AVERAGE DEF:cached=/var/lib/collectd/rrd/localhost/memory/memory-cached.rrd:value:AVERAGE DEF:free=/var/lib/collectd/rrd/localhost/memory/memory-free.rrd:value:AVERAGE DEF:used=/var/lib/collectd/rrd/localhost/memory/memory-used.rrd:value:AVERAGE AREA:used#4169E1:Used:STACK AREA:buffered#32C734:Buffered:STACK AREA:cached#00FF00:Cached:STACK 'AREA:free#FFFFFF:Free\c:STACK' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ temp_graph_imperial /var/www/html/graphs/system-localhost-temperature_imperial-24h.png /var/lib/collectd/rrd/localhost/table-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-temperature_imperial-24h.png --start end-24h --width 480 --height 200 --step '' --title 'Core Temperature' --vertical-label 'Degrees Fahrenheit' --lower-limit 32 --upper-limit 212 --rigid --units-exponent 1 DEF:traw=/var/lib/collectd/rrd/localhost/table-localhost/gauge-cpu_temp.rrd:value:MAX CDEF:tta=traw,1000,/ 'CDEF:ttb=tta,1.8,*' CDEF:ttc=ttb,32,+ AREA:ttc#ffcc00 'COMMENT: \n' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
ERROR: opening '/var/lib/collectd/rrd/localhost/table-localhost/gauge-cpu_temp.rrd': No such file or directory
+ temp_graph_metric /var/www/html/graphs/system-localhost-temperature_metric-24h.png /var/lib/collectd/rrd/localhost/table-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-temperature_metric-24h.png --start end-24h --width 480 --height 200 --step '' --title 'Core Temperature' --vertical-label 'Degrees Celcius' --lower-limit 0 --upper-limit 100 --rigid --units-exponent 1 DEF:traw=/var/lib/collectd/rrd/localhost/table-localhost/gauge-cpu_temp.rrd:value:MAX CDEF:tfin=traw,1000,/ AREA:tfin#ffcc00 'COMMENT: \n' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
ERROR: opening '/var/lib/collectd/rrd/localhost/table-localhost/gauge-cpu_temp.rrd': No such file or directory
+ wlan0_graph /var/www/html/graphs/system-localhost-wlan0_bandwidth-24h.png /var/lib/collectd/rrd/localhost/interface-wlan0 ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/system-localhost-wlan0_bandwidth-24h.png --start end-24h --width 480 --height 200 --step '' --title 'Bandwidth Usage (wlan0)' --vertical-label Bytes/Sec TEXTALIGN:center DEF:rx=/var/lib/collectd/rrd/localhost/interface-wlan0/if_octets.rrd:rx:AVERAGE DEF:tx=/var/lib/collectd/rrd/localhost/interface-wlan0/if_octets.rrd:tx:AVERAGE 'CDEF:tx_neg=tx,-1,*' AREA:rx#32CD32:Incoming LINE1:rx#336600 'GPRINT:rx:MAX:Max\:%8.1lf %s' 'GPRINT:rx:AVERAGE:Avg\:%8.1lf %S' 'GPRINT:rx:LAST:Current\:%8.1lf %Sbytes/sec\c' AREA:tx_neg#4169E1:Outgoing LINE1:tx_neg#0033CC 'GPRINT:tx:MAX:Max\:%8.1lf %S' 'GPRINT:tx:AVERAGE:Avg\:%8.1lf %S' 'GPRINT:tx:LAST:Current\:%8.1lf %Sbytes/sec\c' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ local_rate_graph /var/www/html/graphs/dump1090-localhost-local_rate-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-local_rate-24h.png --start end-24h --width 429 --height 200 --step '' --title 'ADS-B Message Rate' --vertical-label Messages/Second --lower-limit 0 --units-exponent 0 --right-axis 360:0 DEF:messages=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE DEF:strong=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-strong_signals.rrd:value:AVERAGE DEF:positions=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-positions.rrd:value:AVERAGE 'CDEF:y2strong=strong,10,*' 'CDEF:y2positions=positions,10,*' 'LINE1:messages#0000FF:Messages Received' 'AREA:y2strong#FF0000:Messages > -3dBFS / Hr (RHS)' 'LINE1:y2positions#00c0FF:Positions / Hr (RHS)\c' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ local_trailing_rate_graph /var/www/html/graphs/dump1090-localhost-local_trailing_rate-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-local_trailing_rate-24h.png --start end-24h --width 959 --height 200 --step '' --title 'ADS-B Message Rate' --vertical-label Messages/Second --lower-limit 0 --units-exponent 0 --right-axis 360:0 --slope-mode TEXTALIGN:center DEF:messages=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE DEF:a=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE:end=now-86400:start=end-86400 DEF:b=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE:end=now-172800:start=end-86400 DEF:c=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE:end=now-259200:start=end-86400 DEF:d=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE:end=now-345600:start=end-86400 DEF:e=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE:end=now-432000:start=end-86400 DEF:f=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE:end=now-518400:start=end-86400 DEF:g=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:AVERAGE:end=now-604800:start=end-86400 DEF:amin=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MIN:end=now-86400:start=end-86400 DEF:bmin=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MIN:end=now-172800:start=end-86400 DEF:cmin=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MIN:end=now-259200:start=end-86400 DEF:dmin=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MIN:end=now-345600:start=end-86400 DEF:emin=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MIN:end=now-432000:start=end-86400 DEF:fmin=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MIN:end=now-518400:start=end-86400 DEF:gmin=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MIN:end=now-604800:start=end-86400 DEF:amax=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MAX:end=now-86400:start=end-86400 DEF:bmax=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MAX:end=now-172800:start=end-86400 DEF:cmax=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MAX:end=now-259200:start=end-86400 DEF:dmax=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MAX:end=now-345600:start=end-86400 DEF:emax=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MAX:end=now-432000:start=end-86400 DEF:fmax=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MAX:end=now-518400:start=end-86400 DEF:gmax=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd:value:MAX:end=now-604800:start=end-86400 CDEF:a1=a,UN,0,a,IF CDEF:b1=b,UN,0,b,IF CDEF:c1=c,UN,0,c,IF CDEF:d1=d,UN,0,d,IF CDEF:e1=e,UN,0,e,IF CDEF:f1=f,UN,0,f,IF CDEF:g1=g,UN,0,g,IF CDEF:amin1=amin,UN,1000,amin,IF CDEF:bmin1=bmin,UN,1000,bmin,IF CDEF:cmin1=cmin,UN,1000,cmin,IF CDEF:dmin1=dmin,UN,1000,dmin,IF CDEF:emin1=emin,UN,1000,emin,IF CDEF:fmin1=fmin,UN,1000,fmin,IF CDEF:gmin1=gmin,UN,1000,gmin,IF CDEF:amax1=amax,UN,0,amax,IF CDEF:bmax1=bmax,UN,0,bmax,IF CDEF:cmax1=cmax,UN,0,cmax,IF CDEF:dmax1=dmax,UN,0,dmax,IF CDEF:emax1=emax,UN,0,emax,IF CDEF:fmax1=fmax,UN,0,fmax,IF CDEF:gmax1=gmax,UN,0,gmax,IF DEF:strong=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-strong_signals.rrd:value:AVERAGE DEF:positions=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-positions.rrd:value:AVERAGE 'CDEF:y2strong=strong,10,*' 'CDEF:y2positions=positions,10,*' SHIFT:a1:86400 SHIFT:b1:172800 SHIFT:c1:259200 SHIFT:d1:345600 SHIFT:e1:432000 SHIFT:f1:518400 SHIFT:g1:604800 SHIFT:amin1:86400 SHIFT:bmin1:172800 SHIFT:cmin1:259200 SHIFT:dmin1:345600 SHIFT:emin1:432000 SHIFT:fmin1:518400 SHIFT:gmin1:604800 SHIFT:amax1:86400 SHIFT:bmax1:172800 SHIFT:cmax1:259200 SHIFT:dmax1:345600 SHIFT:emax1:432000 SHIFT:fmax1:518400 SHIFT:gmax1:604800 CDEF:7dayaverage=a1,b1,c1,d1,e1,f1,g1,+,+,+,+,+,+,7,/ CDEF:min1=amin1,bmin1,MIN CDEF:min2=cmin1,dmin1,MIN CDEF:min3=emin1,fmin1,MIN CDEF:min4=min1,min2,MIN CDEF:min5=min3,gmin1,MIN CDEF:min=min4,min5,MIN CDEF:max1=amax1,bmax1,MAX CDEF:max2=cmax1,dmax1,MAX CDEF:max3=emax1,fmax1,MAX CDEF:max4=max1,max2,MAX CDEF:max5=max3,gmax1,MAX CDEF:max=max4,max5,MAX CDEF:maxarea=max,min,- 'LINE1:messages#0000FF:Messages Received' LINE1:min#FFFF99 AREA:maxarea#FFFF99:Min/Max:STACK 'LINE1:7dayaverage#00FF00:7 Day Average' LINE1:messages#0000FF 'AREA:y2strong#FF0000:Messages > -3dBFS/Hr (RHS)' 'LINE1:y2positions#00c0FF:Positions/Hr (RHS)\c' --watermark 'Drawn: 01/18/17 14:44 CST'
1107x284
+ range_graph_imperial_nautical /var/www/html/graphs/dump1090-localhost-range_imperial_nautical-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-range_imperial_nautical-24h.png --start end-24h --width 428 --height 200 --step '' --title 'ADS-B Max Range' --vertical-label 'Nautical Miles' --units-exponent 0 --right-axis 1.852:0 --right-axis-label Kilometres DEF:rangem=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_range-max_range.rrd:value:MAX 'CDEF:rangekm=rangem,0.001,*' 'CDEF:rangenm=rangekm,0.539956803,*' 'LINE1:rangenm#0000FF:Max Range' VDEF:avgrange=rangenm,AVERAGE 'LINE1:avgrange#666666:Avr Range\::dashes' VDEF:peakrange=rangenm,MAXIMUM 'GPRINT:avgrange:%1.1lf NM' 'LINE1:peakrange#FF0000:Peak Range\:' 'GPRINT:peakrange:%1.1lf NM\c' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ range_graph_imperial_statute /var/www/html/graphs/dump1090-localhost-range_imperial_statute-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-range_imperial_statute-24h.png --start end-24h --width 428 --height 200 --step '' --title 'ADS-B Max Range' --vertical-label 'Statute Miles' --units-exponent 0 --right-axis 1.609:0 --right-axis-label Kilometres DEF:rangem=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_range-max_range.rrd:value:MAX 'CDEF:rangekm=rangem,0.001,*' 'CDEF:rangesm=rangekm,0.621371,*' 'LINE1:rangesm#0000FF:Max Range' VDEF:avgrange=rangesm,AVERAGE 'LINE1:avgrange#666666:Avr Range\::dashes' VDEF:peakrange=rangesm,MAXIMUM 'GPRINT:avgrange:%1.1lf SM' 'LINE1:peakrange#FF0000:Peak Range\:' 'GPRINT:peakrange:%1.1lf SM\c' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ range_graph_metric /var/www/html/graphs/dump1090-localhost-range_metric-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-range_metric-24h.png --start end-24h --width 428 --height 200 --step '' --title 'ADS-B Max Range' --vertical-label Kilometres --units-exponent 0 --right-axis 0.5399:0 --right-axis-label 'Nautical Miles' DEF:rangem=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_range-max_range.rrd:value:MAX 'CDEF:range=rangem,0.001,*' 'LINE1:range#0000FF:Max Range' VDEF:avgrange=range,AVERAGE 'LINE1:avgrange#666666:Avg Range\::dashes' VDEF:peakrange=range,MAXIMUM 'GPRINT:avgrange:%1.1lf km' 'LINE1:peakrange#FF0000:Peak Range\:' 'GPRINT:peakrange:%1.1lf km\c' 'COMMENT: \n' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298
+ signal_graph /var/www/html/graphs/dump1090-localhost-signal-24h.png /var/lib/collectd/rrd/localhost/dump1090-localhost ADS-B 24h ''
+ rrdtool graph /var/www/html/graphs/dump1090-localhost-signal-24h.png --start end-24h --width 480 --height 186 --step '' --title 'ADS-B Signal Level' --vertical-label dBFS --upper-limit 1 --lower-limit -45 --rigid --units-exponent 0 TEXTALIGN:center DEF:signal=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-signal.rrd:value:AVERAGE DEF:peak=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-peak_signal.rrd:value:AVERAGE DEF:noise=/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-noise.rrd:value:AVERAGE CDEF:us=signal,UN,-100,signal,IF 'AREA:-100#00FF00:Mean Level\:' AREA:us#FFFFFF GPRINT:signal:AVERAGE:%4.1lf 'LINE1:peak#0000FF:Peak Level\:' 'GPRINT:peak:MAX:%4.1lf\c' LINE:noise#7F00FF:Noise 'GPRINT:noise:MAX:Max\: %4.1lf' 'GPRINT:noise:MIN:Min\: %4.1lf' $GPRINT:noise:AVERAGE:Avg\: %4.1lf\c' 'LINE1:0#000000:Zero dBFS' 'LINE1:-3#FF0000:-3 dBFS\c' --watermark 'Drawn: 01/18/17 14:44 CST'
577x298

As to the other one, I'll try and dig up the log and make an issue for it here.

**Comment by Romeo-Golf** [comment]
hmm graph generation looks fine, just to check you arent somehow blocking javascript in your browser?

If not then can you share the output of the following:

curl http://localhost/graphs.php

sudo ls -lR /var/lib/collectd/rrd/localhost/

**Comment by ForestFeather** [comment]
Let's go with the last one first:
```
/var/lib/collectd/rrd/localhost/:
total 0
drwxr-xr-x 2 root root  744 Jan  2 06:37 aggregation-cpu-average
drwxr-xr-x 2 root root  640 Jan  2 06:31 df-root
drwxr-xr-x 2 root root 1864 Jan  4 21:33 dump1090-localhost
drwxr-xr-x 2 root root  376 Jan  2 06:31 interface-wlan0
drwxr-xr-x 2 root root  464 Jan  2 06:31 memory

/var/lib/collectd/rrd/localhost/aggregation-cpu-average:
total 1216
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-idle.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-interrupt.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-nice.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-softirq.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-steal.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-system.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-user.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 cpu-wait.rrd

/var/lib/collectd/rrd/localhost/df-root:
total 912
-rw-r--r-- 1 root root 154692 Jan 18 15:36 df_complex-free.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 df_complex-reserved.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 df_complex-used.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 df_inodes-free.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 df_inodes-reserved.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 df_inodes-used.rrd

/var/lib/collectd/rrd/localhost/dump1090-localhost:
total 3040
-rw-r--r-- 1 root root 307516 Jan 18 15:36 dump1090_aircraft-recent.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_cpu-background.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_cpu-demod.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_cpu-reader.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_dbfs-noise.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_dbfs-peak_signal.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_dbfs-signal.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-local_accepted_0.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-local_accepted_1.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-local_accepted.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-positions.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-remote_accepted_0.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-remote_accepted_1.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-remote_accepted.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_messages-strong_signals.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_mlat-recent.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_range-max_range.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_tracks-all.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 dump1090_tracks-single_message.rrd

/var/lib/collectd/rrd/localhost/interface-wlan0:
total 912
-rw-r--r-- 1 root root 307516 Jan 18 15:36 if_errors.rrd
-rw-r--r-- 1 root root 307516 Jan 18 15:36 if_octets.rrd
-rw-r--r-- 1 root root 307516 Jan 18 15:36 if_packets.rrd

/var/lib/collectd/rrd/localhost/memory:
total 608
-rw-r--r-- 1 root root 154692 Jan 18 15:36 memory-buffered.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 memory-cached.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 memory-free.rrd
-rw-r--r-- 1 root root 154692 Jan 18 15:36 memory-used.rrd
```
And here's the curl output - looks all normal here.

```
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <title>KE0IYN's ADS-B Receiver: Performance Graphs</title>
        <meta http-equiv="cache-control" content="no-cache" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/templates/default/assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="/templates/default/assets/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="/templates/default/assets/css/portal.css">
        
        
    </head>
        <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">KE0IYN's ADS-B Receiver</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            
                            <li id="flights-link"><a href="/flights.php">Flights</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">System <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li id="graphs-link"><a href="/graphs.php">Performance Graphs</a></li>
                                    <li id="system-link"><a href="/system.php">System Information</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Maps <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li id="dump1090-link"><a href="/dump1090.php">Live Dump1090 Map</a></li>
                                    
                                    <li id="planefinder-link"><a href="http://localhost:30053" target="_blank">Plane Finder Client</a></li>
                                </ul>
                            </li>
                            
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Links <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    
                                </ul>
                            </li>
                            
                        </ul>
                        
                        <form name="search" method="post" action="flights.php" class="navbar-form navbar-right">
                            <div class="form-group">
                                <input type="text" name="flight" placeholder="Flight" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-success">Search</button>
                        </form>
                        
                    </div>
                </div>
            </nav>
            
            
            <div class="container">
                <h1>Performance Graphs</h1>
                <div class="btn-group" role="group">
                    <button type="button" id="btn-1h" class="btn btn-default btn-sm active" onclick="switchView('1h')">Hourly</button>
                    <button type="button" id="btn-6h" class="btn btn-default btn-sm" onclick="switchView('6h')">Six Hours</button>
                    <button type="button" id="btn-24h" class="btn btn-default btn-sm" onclick="switchView('24h')">Daily</button>
                    <button type="button" id="btn-7d" class="btn btn-default btn-sm" onclick="switchView('7d')">Weekly</button>
                    <button type="button" id="btn-30d" class="btn btn-default btn-sm" onclick="switchView('30d')">Monthly</button>
                    <button type="button" id="btn-365d" class="btn btn-default btn-sm" onclick="switchView('365d')">Yearly</button>
                </div>
                <div class="padding"></div>
                <!-- Dump1090 Graphs -->
                <div class="panel panel-default">
                    <div class="panel-heading">Dump1090 Graphs</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <a id ="dump1090-local_trailing_rate-link" href="#">
                                    <img id="dump1090-local_trailing_rate-image" class="img-responsive" src="#" alt="Message Rate (Trailing)">
                                </a>
                            </div>
                        </div>
                        <div class="padding"></div>
                        <div class="row">
                            <div class="col-md-6 text-center">
                                <a id ="dump1090-aircraft-link" href="#">
                                   <img id="dump1090-aircraft-image" class="img-responsive" src="#" alt="Aircraft Seen">
                                </a>
                            </div>
                            <div class="col-md-6 text-center">
                                <a id ="dump1090-tracks-link" href="#">
                                   <img id="dump1090-tracks-image" class="img-responsive" src="#" alt="Tracks Seen">
                                </a>
                            </div>
                        </div>
                        <div class="padding"></div>
                        <div class="row">
                            
                            <div class="col-md-6 text-center">
                                <a id ="dump1090-range_imperial_nautical-link" href="#">
                                    <img id="dump1090-range_imperial_nautical-image" class="img-responsive" src="#" alt="Max Range (Nautical Miles)">
                                </a>
                            </div>
                            
                            
                            
                            <div class="col-md-6 text-center">
                                <a id ="dump1090-signal-link" href="#">
                                    <img id="dump1090-signal-image" class="img-responsive" src="#" alt="Signal Level">
                                </a>
                            </div>
                        </div>
                        <div class="padding"></div>
                        <div class="row">
                            <div class="col-md-6 text-center">
                                <a id ="dump1090-local_rate-link" href="#">
                                   <img id="dump1090-local_rate-image" class="img-responsive" src="#" alt="Message Rate">
                                </a>
                            </div>
                            <div class="col-md-6 text-center">
                                <a id ="dump1090-aircraft_message_rate-link" href="#">
                                    <img id="dump1090-aircraft_message_rate-image" class="img-responsive" src="#" alt="Aircraft Message Rate">
                                </a>
                            </div>
                        </div>
                        <div class="padding"></div>
                        <div class="row">
                            <div class="col-md-6 text-center">
                                <a id ="dump1090-cpu-link" href="#">
                                    <img id="dump1090-cpu-image" class="img-responsive" src="#" alt="CPU Utilization">
                                </a>
                            </div>
                            <div class="col-md-6 text-center"></div>
                        </div>
                    </div>
                </div>
                <!-- System Graphs -->
                <div class="panel panel-default">
                    <div class="panel-heading">System Graphs</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <a id ="system-cpu-link" href="#">
                                    <img id="system-cpu-image" class="img-responsive" src="#" alt="Overall CPU Utilization">
                                </a>
                            </div>
                        </div>
                        <div class="padding"></div>
                        <div class="row">
                            
                            <div class="col-md-6 text-center">
                                <a id ="system-temperature_imperial-link" href="#">
                                   <img id="system-temperature_imperial-image" class="img-responsive" src="#" alt="Core Temperature">
                                </a>
                            </div>
                            
                            
                            <div class="col-md-6 text-center">
                                <a id ="system-memory-link" href="#">
                                   <img id="system-memory-image" class="img-responsive" src="#" alt="Memory Utilization">
                                </a>
                            </div>
                        </div>
                        <div class="padding"></div>
                        <div class="row">
                            
                            <div class="col-md-6 text-center">
                                <a id ="system-wlan0_bandwidth-link" href="#">
                                   <img id="system-wlan0_bandwidth-image" class="img-responsive" src="#" alt="Bandwidth Usage (wlan0)">
                                </a>
                            </div>
                            
                            <div class="col-md-6 text-center">
                                <a id ="system-df_root-link" href="#">
                                    <img id="system-df_root-image" class="img-responsive" src="#" alt="Disk Space Usage (/)">
                                </a>
                            </div>
                        </div>
                        <div class="padding"></div>
                        <div class="row">
                            <div class="col-md-6 text-center">
                                <a id ="system-disk_io_iops-link" href="#">
                                    <img id="system-disk_io_iops-image" class="img-responsive" src="#" alt="Disk I/O - IOPS">
                                </a>
                            </div>
                            <div class="col-md-6 text-center">
                                <a id ="system-disk_io_octets-link" href="#">
                                    <img id="system-disk_io_octets-image" class="img-responsive" src="#" alt="Disk I/O - Bandwidth">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="push"></div>
        </div>
        <footer id="footer">
            <div class="container">
                <p class="muted credits">
                    <a href="https://www.adsbreceiver.net">The ADS-B Receiver Project</a>
                </p>
            </div>
        </footer>
        <script src="/templates/default/assets/js/jquery-3.1.1.min.js"></script>
        <script src="/templates/default/assets/js/bootstrap.min.js"></script>
        
        <script type="text/javascript">
            $('#graphs-link').addClass("active");
        </script>
        
        <script src="/templates/default/assets/js/graphs.js"></script>

   </body>
</html>
```

**Comment by ForestFeather** [comment]
As a note, the path you're checking with /sys/class/hwmon/hwmon0/temp1_input is in fact nonexistent.  Nothing is under hwmon folder on the CHIP.

**Comment by ForestFeather** [comment]
Another note on this - we may not be able to get the IOPS stats at all.  Apparently, collectd relies on /proc/diskstats to be populated, but the file is empty.  This is something that there's an issue on the CHIP forums about, but no response or any other information.

**Comment by Romeo-Golf** [comment]
hmm, how about /sys/class/thermal/ ?

Any chance you could post on their forum to see if we can get a defiantive answer?  :)

 https://bbs.nextthing.co/t/how-to-check-the-temperature-of-chip/1738/45

**Comment by ForestFeather** [comment]
Okay, color me annoyed, and possibly having to reinstall the whole thing.

I went to another one of my CHIPs that is newer (the one I'm on is an Alpha Chip, the early ones from Kickstarter).  The newer models do in fact have hwmon on them, and the requisite files.  /proc/diskstats is also populated, but whether it's the ubi filesystem or something else, all entries are 0.

Getting those charts to work on a CHIP may be a bit harder than we originally thought, at least IOPS.

I'll do some reading and see if I can't find out if it's a side effect of the older hardware or what.

**Comment by Romeo-Golf** [comment]
Interesting.. I'll try to dig mine out but it was also from KS so may also be an early hardware revision :(

**Comment by ForestFeather** [comment]
So... reading further,  I've confirmed that as of right now collectd does not support ubi-type filesystems.  Which are the ones made for embedded NAND flash style memory.  They just don't report the same kind of stats apparently, yet, to the kernel, so we won't get that.

Still hunting on other info for the CHIP thermal stuff, but the one comment I saw about it had zero responses.  Everyone seems to rely on the ax209 for thermal.
