### ISSUE TITLE
Web Portal install fails - wrong detection of OS version on Stretch & Ubuntu

### ISSUE THREAD

**Issue by abcd567a** [jprochazka/adsb-receiver#443]
### (1) When trying to install web portal on Raspbian STRETCH and UBUNTU 18.04 following error output is given:
```
The ADS-B Receiver Project v2.6.1 Installer
  Setting up the ADS-B Receiver Project Portal...
  ------------------------------------------------------------------------------
  Installing packages needed to fulfill dependencies...

  Checking if the package lighttpd is installed... [OK]
  Checking if the package php5-cgi is installed... [NOT INSTALLED]
  Installing the package php5-cgi...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-cgi' has no installation candidate
....................
....................
E: Package 'php5-cgi' has no installation candidate

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "php5-cgi" could not be installed in 5 attempts.

    ANY FURTHER SETUP AND/OR INSTALLATION REQUESTS HAVE BEEN TERMINIATED
```

## (2) The problem is in following snippet of file `adsb-receiver/bash/portal/install.sh`:

```
## CHECK FOR PREREQUISITE PACKAGES

DISTRO_PHP_VERSION="5"
case $RECEIVER_OS_DISTRIBUTION in
    debian|raspbian)
        if [[ $RECEIVER_OS_RELEASE -ge "9" ]]; then DISTRO_PHP_VERSION="7.0"; fi
        ;;
    ubuntu)
        if [ `bc -l <<< "$RECEIVER_OS_RELEASE >= 16.04"` -eq 1 ]; then DISTRO_PHP_VERSION="7.0"; fi
        if [ `bc -l <<< "$RECEIVER_OS_RELEASE >= 17.10"` -eq 1 ]; then DISTRO_PHP_VERSION="7.1"; fi
        ;;
esac
```

## (3) Fixed it by following modifications in above code - Tested on Raspbain STRETCH and UBUNTU 18.04 amd64, works ok:
(1) added line `. /etc/os-release`  
(2) Changed variable name from `$RECEIVER_OS_DISTRIBUTION` to `$ID` 
(3) Changed variable name  from `$RECEIVER_OS_RELEASE` to `$VERSION_ID`.

.
```
## CHECK FOR PREREQUISITE PACKAGES

DISTRO_PHP_VERSION="5"

. /etc/os-release

#case $RECEIVER_OS_DISTRIBUTION in
case $ID in
    debian|raspbian)
#        if [[ $RECEIVER_OS_RELEASE -ge "9" ]]; then DISTRO_PHP_VERSION="7.0"; fi
        if [[ $VERSION_ID -ge "9" ]]; then DISTRO_PHP_VERSION="7.0"; fi
        ;;
    ubuntu)
#        if [ `bc -l <<< "$RECEIVER_OS_RELEASE >= 16.04"` -eq 1 ]; then DISTRO_PHP_VERSION="7.0"; fi
#        if [ `bc -l <<< "$RECEIVER_OS_RELEASE >= 17.10"` -eq 1 ]; then DISTRO_PHP_VERSION="7.1"; fi

        if [ `bc -l <<< "$VERSION_ID >= 16.04"` -eq 1 ]; then DISTRO_PHP_VERSION="7.0"; fi
        if [ `bc -l <<< "$VERSION_ID >= 17.10"` -eq 1 ]; then DISTRO_PHP_VERSION="7.1"; fi
        ;;
esac
```

**Comment by Conan179** [comment]
Why 2.6.1 and not 2.6.2?

When I installed it on my Pi with Stretch (image I downloaded on 5.6. "2018-04-18-raspbian-stretch") I did not have this error.

**Comment by Conan179** [comment]
v2.6.2 (April 6th, 2018)
Fixed so Ubunbtu 17.10 and higher properly installs PHP 7.1 and its related packages.

**Comment by abcd567a** [comment]
I just now cloned  `git clone https://jprochazka/adsb-receiver.git` and checked in file `adsb-receiver/bash/portal/install.sh` and code is identical. It is not fixed yet.
```
## CHECK FOR PREREQUISITE PACKAGES

DISTRO_PHP_VERSION="5"
case $RECEIVER_OS_DISTRIBUTION in
    debian|raspbian)
        if [[ $RECEIVER_OS_RELEASE -ge "9" ]]; then DISTRO_PHP_VERSION="7.0"; fi
        ;;
    ubuntu)
        if [ `bc -l <<< "$RECEIVER_OS_RELEASE >= 16.04"` -eq 1 ]; then DISTRO_PHP_VERSION="7.0"; fi
        if [ `bc -l <<< "$RECEIVER_OS_RELEASE >= 17.10"` -eq 1 ]; then DISTRO_PHP_VERSION="7.1"; fi
        ;;
esac
```

**Comment by jprochazka** [comment]
This should no longer be an issue as of v2.6.2... I actually just finished testing v2.6.3 on Debian Stretch with no issues. The variables RECEIVER_OS_DISTRIBUTION and RECEIVER_OS_RELEASE are set in lines 47 and 48 of ~/adsb-receiver/install.sh and exported to the environment.

```
export RECEIVER_OS_DISTRIBUTION=`. /etc/os-release; echo ${ID/*, /}`
export RECEIVER_OS_RELEASE=`. /etc/os-release; echo ${VERSION_ID/*, /}`
```

Which should result in the following values for these variables:

**Debian Stretch**
$RECEIVER_OS_DISTRIBUTION = debian
$RECEIVER_OS_RELEASE = 9

**Ubuntu 18.04 LTS**
$RECEIVER_OS_DISTRIBUTION = ubuntu
$RECEIVER_OS_RELEASE = 18.04

Please check that these lines do in fact exist in your copy of ~/adsb-receiver/install.sh and ~/adsb-receiver/bash/portal/install.sh is not being executed directly.

BTW I did update the version reported at the top of the install scripts for v2..6.3 which I noticed I omitted in v2.6.2...

**Comment by abcd567a** [comment]
Thanks.

**Comment by jprochazka** [comment]
All good then?

**Comment by abcd567a** [comment]
Yes, tried on fresh install (Raspbian Stretch). All ok. Actually I was trying on Flightradar24 Pi24 image, and they have modified $ID to pi24-raspbian

**Comment by abcd567a** [comment]
Now I tried it on Ubuntu 18.04 on i386 machine. The script correctly detected OS and Version, and tried to install php7.1-cgi, but gave error message _"php7.1-cgi has no installation candidate"_ , and installation  aborted.

**Comment by jprochazka** [comment]
Fixed in commit e11bbcea5d60406b5439218099251436a345ba92

**Comment by abcd567a** [comment]
Thanks. 
Now I am away from home, will try on Ubuntu 18.04 amd64 tonight, by first deleting folder `/home/pi/adsb-receiver`, then cloning again `git clone https://github.com/jprochazka/adsb-receiver.git`

The Pi24 image is a bit tricky because in file `/etc/os-release`, they have modified `$ID` from `raspbian` to `pi24-raspbian`. :(

**Comment by jprochazka** [comment]
It will still be broken on the Flightradar24's pi24-raspbian "distro". I am at a loss as to why they would do this making it out like they develop their own distro being I am sure they are pulling packages directly from the Raspbian package repositories and only added their own strictly to update their software.

To each their own I guess...
